### ISSUE TITLE
Add custom gitlab URL

### ISSUE THREAD

**Issue by alebec** [FriendsOfFlarum/auth-gitlab#4]
Hello, 

Is it possible to add an option for a custom gitlab domain (with gitlab CE) ?

I can add it in src/Controllers/GitLabAuthController.php but i don't know how to make it configurable.
```
return new Gitlab([
            'clientId'        => $this->settings->get('fof-auth-gitlab.client_id'),
            'clientSecret' => $this->settings->get('fof-auth-gitlab.client_secret'),
            'redirectUri'  => $redirectUri,
            'domain'       => 'https://mygitlab.myhost.com',
        ]);
```

**Comment by Ralkage** [comment]
Hi @alebec, I am looking to add this as an option in an upcoming release but first I am going to have to test it on my end :)

I'll keep you updated and ask for feedback if needed.

**Comment by Ralkage** [comment]
#9 didn't include the production JS build changes so I'll have to fix that and possibly revert to using the non-fof-component way of adding a settings modal because I'm currently having issues with the @fof/components package 🙈

**Comment by Ralkage** [comment]
@Braintelligence fixed the issue with using the latest @fof/components package, some changes were made in that package and I finally figured out what I needed to change/add to get things working again 😄 

I'm gonna attempt to work on [your suggestions](https://github.com/FriendsOfFlarum/auth-gitlab/pull/9#issuecomment-678635008) (I need to test both), but I eventually will announce that as of beta 14, this extension will no longer be updated and will be superseded by [fof/oauth](https://github.com/FriendsOfFlarum/oauth). I will make a more formal announcement on Flarum Discuss once I tag a new release 👀

**Comment by Braintelligence** [comment]
Does fof/oauth already support self-hosted Gitlab? The readme is super-short...

**Comment by Ralkage** [comment]
> Does fof/oauth already support self-hosted Gitlab? The readme is super-short...

It does not, in its current state anyways. But rest assured [I already have an feature enhancement on the works](https://github.com/FriendsOfFlarum/oauth/issues/2#issuecomment-694742036) to keep as a reminder to add this optional feature :)

For now, I’m gonna close this issue, feel free to chime in on that discussion going on in that issue I just linked ;)
